const lang = {
    access: {
        en: "Unlimited Access<br>to All Features",
        es: "Acceso ilimitado<br>a todas las funciones",
        fr: "Accès illimité<br>à toutes les fonctionnalités",
        ja: "全ての機能へ<br>無制限アクセス",
        nl: "Onbeperkte toegang<br>tot alle functies",
        ru: "Неограниченный доступ<br>ко всем функциям",
        zh: "无限制使用<br>所有功能",
    },
    docs: {
        en: "Unlimited documents",
        es: "Documentos ilimitados",
        fr: "Documents illimités",
        ja: "無制限のドキュメント",
        nl: "Onbeperkt aantal documenten",
        ru: "Любое количество документов",
        zh: "文档无限制",
    },
    cloud: {
        en: "Export to clouds",
        es: "Exportar a las nubes",
        fr: "Exporter vers les nuages",
        ja: "クラウドへのエクスポート",
        nl: "Exporteren naar clouds",
        ru: "Экспорт в облако",
        zh: "导出到云",
    },
    count: {
        en: "Count mode",
        es: "Modo de recuento",
        fr: "Mode décompte",
        ja: "カウントモード",
        nl: "Aantal modus",
        ru: "Режим «Подсчет»",
        zh: "计数模式",
    },
    recognition: {
        en: "Text recognition (OCR)",
        es: "Reconocimiento de texto (OCR)",
        fr: "Reconnaissance de texte (OCR)",
        ja: "テキスト認識 (OCR)",
        nl: "Gratis tekstherkenning (OCR)",
        ru: "Распознавание текста (OCR)",
        zh: "文本识别（OCR）",
    },
    monthly: {
        en: "Monthly",
        es: "Mensual",
        fr: "Tous les mois",
        ja: "月次",
        nl: "Maandelijks",
        ru: "1 месяц",
        zh: "每月",
    },
    pricePerMonth: {
        en: "$9.99<br>per month",
        es: "$9.99<br>por mes",
        fr: "$9.99<br>par mois",
        ja: "$9.99<br>/月",
        nl: "$9.99<br>per maand",
        ru: "$9.99<br>в месяц",
        zh: "$9.99每月<br>",
    },
    pricePerMonthYear: {
        en: "$1.66/month",
        es: "$1.66/mes",
        fr: "$1.66/mois",
        ja: "$1.66/か月",
        nl: "$1.66/maand",
        ru: "$1.66/месяц",
        zh: "$1.66/月",
    },
    freeDays: {
        en: "3 DAYS FREE",
        es: "3 DÍAS GRATIS",
        fr: "3 JOURS GRATUITS",
        ja: "3日間無料",
        nl: "3 DAGEN GRATIS",
        ru: "3 ДНЯ БЕСПЛАТНО",
        zh: "3日免费",
    },
    perMonth: {
        en: "$9.99/month",
        es: "$9.99/mes",
        fr: "$9.99/mois",
        ja: "$9.99/か月",
        nl: "$9.99/maand",
        ru: "$9.99/месяц",
        zh: "$9.99/月",
    },
    annually: {
        en: "Annually",
        es: "Anual",
        fr: "Tous les ans",
        ja: "年次",
        nl: "Jaarlijks",
        ru: "1 ГОД",
        zh: "包年",
    },
    perYear: {
        en: "$19.99<br>per year",
        es: "$19.99<br>por año",
        fr: "$19.99<br>par an",
        ja: "$19.99<br>/年",
        nl: "$19.99<br>per jaar",
        ru: "$19.99<br>в год",
        zh: "每年 $19.99<br>",
    },
    popular: {
        en: "MOST POPULAR",
        es: "LO MÁS PEDIDO",
        fr: "LE PLUS POPULAIRE",
        ja: "一番人気",
        nl: "MEEST POPULAIR",
        ru: "ПОПУЛЯРНОЕ",
        zh: "最热门",
    },
    link: {
        en: "Continue",
        es: "Continuar",
        fr: "Continuer",
        ja: "続行する",
        nl: "Doorgaan",
        ru: "Продолжить",
        zh: "继续",
    },
    renewable: {
        en: "Auto-renewable. Cancel anytime.",
        es: "Renovable automáticamente. Cancela cuando quieras.",
        fr: "Renouvelable automatiquement. Annulez à tout moment.",
        ja: "自動更新可能。いつでもキャンセル可能。",
        nl: "Automatisch verlengbaar. Altijd annuleren.",
        ru: "Автопродление. Отмена в любое время.",
        zh: "自动续订。可随时取消。",
    },
    terms: {
        en: "Terms of Use",
        es: "Términos de uso",
        fr: "Conditions d'utilisation",
        ja: "利用規約",
        nl: "Gebruiksvoorwaarden",
        ru: "Условия использования",
        zh: "使用条款",
    },
    restore: {
        en: "Restore",
        es: "Restablecer",
        fr: "Restaurer",
        ja: "復元する",
        nl: "Herstellen",
        ru: "Восстановить",
        zh: "恢复",
    },
    policy: {
        en: "Privacy Policy",
        es: "Política de privacidad",
        fr: "Politique de confidentialité",
        ja: "プライバシーポリシー",
        nl: "Privacybeleid",
        ru: "Конфиденциальность",
        zh: "隐私政策",
    }
}